export const CALIBRATION_TEMPERATURE_FLAG = "CALIBRATION_TEMPERATURE";

/**
 * Backtest (448 matches, World Cups 1998-2022, xg-v2.2-mismatch-spread):
 * T=0.65 minimized Brier (0.590082), with Log Loss 1.002071, RPS 0.195204,
 * Accuracy 55.58%, and 1-1 as modal score in 1.79% of matches (T=1: 92.41%).
 * Generated by scripts/calibrate-temperature.ts on 2026-06-18.
 * A temperature below 1 divides both lambdas by a smaller value, increasing
 * their absolute separation (and the total goal rate) while preserving their ratio.
 */
export const RECOMMENDED_CALIBRATION_TEMPERATURE = 0.65;

export interface CalibratedLambdas {
  lambdaHomeCal: number;
  lambdaAwayCal: number;
}

export function applyTemperature(
  lambdaHome: number,
  lambdaAway: number,
  temperature: number
): CalibratedLambdas {
  assertLambda(lambdaHome, "lambdaHome");
  assertLambda(lambdaAway, "lambdaAway");
  if (!Number.isFinite(temperature) || temperature <= 0) {
    throw new RangeError("temperature must be a finite positive number.");
  }

  return {
    lambdaHomeCal: Math.max(0.1, lambdaHome / temperature),
    lambdaAwayCal: Math.max(0.1, lambdaAway / temperature),
  };
}

export function resolveCalibrationTemperature(
  explicitValue?: number | string | null,
  environmentValue: string | undefined = process.env[CALIBRATION_TEMPERATURE_FLAG]
): number {
  const requested = explicitValue ?? environmentValue;
  if (requested == null || requested === "") return RECOMMENDED_CALIBRATION_TEMPERATURE;
  const parsed = typeof requested === "number" ? requested : Number(requested);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : RECOMMENDED_CALIBRATION_TEMPERATURE;
}

function assertLambda(value: number, name: string): void {
  if (!Number.isFinite(value) || value < 0) {
    throw new RangeError(`${name} must be a finite non-negative number.`);
  }
}
