import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const YEARS = [1998, 2002, 2006, 2010, 2014, 2018, 2022] as const;
const START_DATES: Record<number, string> = {
  1998: "1998-06-10", 2002: "2002-05-31", 2006: "2006-06-09", 2010: "2010-06-11",
  2014: "2014-06-12", 2018: "2018-06-14", 2022: "2022-11-20",
};
const CODE_MAP: Record<string, string> = {
  AO: "ANG", AR: "ARG", AT: "AUT", AU: "AUS", BA: "BIH", BE: "BEL", BG: "BUL", BR: "BRA",
  CA: "CAN", CH: "SUI", CI: "CIV", CL: "CHI", CM: "CMR", CN: "CHN", CO: "COL", CR: "CRC",
  CZ: "CZE", DE: "GER", DK: "DEN", DZ: "ALG", EC: "ECU", EG: "EGY", EN: "ENG", ES: "ESP",
  FR: "FRA", GH: "GHA", GR: "GRE", HN: "HON", HR: "CRO", IE: "IRL", IR: "IRN", IS: "ISL",
  IT: "ITA", JM: "JAM", JP: "JPN", KP: "PRK", KR: "KOR", MA: "MAR", MX: "MEX", NG: "NGA",
  NL: "NED", NO: "NOR", NZ: "NZL", PA: "PAN", PE: "PER", PL: "POL", PT: "POR", PY: "PAR",
  QA: "QAT", RM: "SCG", RO: "ROU", RS: "SRB", RU: "RUS", SA: "KSA", SE: "SWE", SI: "SVN",
  SK: "SVK", SN: "SEN", SQ: "SCO", TG: "TOG", TN: "TUN", TR: "TUR", TT: "TRI", UA: "UKR",
  US: "USA", UY: "URU", WA: "WAL", YU: "YUG", ZA: "RSA",
};

interface EloRow { worldCup: number; date: string; team: string; elo: number; sourceUrl: string }

void main();

async function main(): Promise<void> {
  const rows: EloRow[] = [];
  for (const worldCup of YEARS) {
    const sourceUrl = `https://www.eloratings.net/${worldCup}_World_Cup_start.tsv`;
    const response = await fetch(sourceUrl);
    if (!response.ok) throw new Error(`Could not fetch ${sourceUrl}: HTTP ${response.status}`);
    const lines = (await response.text()).trim().split(/\r?\n/);
    if (lines.length !== 32) throw new Error(`${sourceUrl} returned ${lines.length} teams; expected 32.`);
    for (const line of lines) {
      const fields = line.split("\t");
      const team = CODE_MAP[fields[2]];
      const elo = Number(fields[3]);
      if (!team || !Number.isFinite(elo)) throw new Error(`Invalid Elo row: ${line}`);
      rows.push({ worldCup, date: START_DATES[worldCup], team, elo, sourceUrl });
    }
  }
  const output = resolve("data/elo-ratings.json");
  const moduleOutput = resolve("src/lib/stat-model/elo-ratings-data.ts");
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, `${JSON.stringify(rows, null, 2)}\n`, "utf8");
  writeFileSync(moduleOutput, `// Generated by scripts/fetch-elo-ratings.ts; data/elo-ratings.json is the canonical artifact.\nexport const ELO_RATING_ROWS = ${JSON.stringify(rows, null, 2)} as const;\n`, "utf8");
  console.log(`Wrote ${rows.length} pre-tournament Elo rows to ${output} and ${moduleOutput}.`);
}
